apiVersion: v1
kind: Namespace
metadata:
  name: avanzando
  labels:
    name: avanzando
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avanzando-config
  namespace: avanzando
data:
  FLASK_ENV: "production"
  CORS_ORIGINS: "https://avanzando.app,https://www.avanzando.app"
  REDIS_URL: "redis://avanzando-redis:6379/0"
  DATABASE_URL: "postgresql://avanzando_user:$(POSTGRES_PASSWORD)@avanzando-postgres:5432/avanzando_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: avanzando-secrets
  namespace: avanzando
type: Opaque
data:
  # Base64 encoded secrets - cambiar en producción
  POSTGRES_PASSWORD: YXZhbnphbmRvX3Bhc3N3b3JkXzEyMw==
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMTIz
  JWT_SECRET_KEY: c3VwZXJfc2VjcmV0X2p3dF9rZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb24=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avanzando-postgres
  namespace: avanzando
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avanzando-postgres
  template:
    metadata:
      labels:
        app: avanzando-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "avanzando_db"
        - name: POSTGRES_USER
          value: "avanzando_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: avanzando-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: avanzando-postgres
  namespace: avanzando
spec:
  selector:
    app: avanzando-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: avanzando
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

